image: ubuntu:18.04

pages:
    script:
    - apt-get update
    - DEBIAN_FRONTEND=noninteractive apt-get install -y python3.7-tk tk-dev python3.7 python3-pip python3-setuptools python3.7-dev python3.7-venv libffi-dev libssl-dev pandoc libgmp3-dev libzbar-dev tesseract-ocr xsel libpoppler-cpp-dev libenchant-2-dev git
    - python3.7 setup.py install
    - export TERM=linux && export TERMINFO=/etc/terminfo && make -C docs html
    - mv ./docs/build/html public
    artifacts:
        paths:
        - public
    only:
    - master

